import test from 'node:test';
import assert from 'node:assert/strict';
import {ruleIntent,resolveIntent,validateIntent,recommendCourses,plainCourse} from '../cloudflare/assistant.mjs';
const first={id:1,title:'书法入门',category:'传统艺术',tags:'书法,安静',description:'学习坐姿和基本笔画。',location:'二楼书画室',level:'初级',fee:0,remaining:3,sessions:[{start_at:'2026-10-10T01:00:00Z',end_at:'2026-10-10T03:00:00Z'}]};
test('negative interests, free preference and unavailable periods are extracted',()=>{const i=ruleIntent('不想学音乐，只能上午去，下午不行，零基础，不想花钱');assert.ok(i.excludeInterests.includes('音乐'));assert.equal(i.interests.includes('音乐'),false);assert.deepEqual(i.periods,['上午']);assert.ok(i.avoidPeriods.includes('下午'));assert.equal(i.freeOnly,true)});
test('time constraints check all sessions and do not silently relax',async()=>{const other={...first,id:2,sessions:[...first.sessions,{start_at:'2026-10-12T06:00:00Z',end_at:'2026-10-12T08:00:00Z'}]};const i=ruleIntent('周末上午免费书法课');const d=await recommendCourses([first,other],i,()=>false);assert.deepEqual(d.results.map(c=>c.id),[1]);assert.ok(d.excluded.find(c=>c.id===2).reasons.length);const empty=await recommendCourses([other],i,()=>false);assert.equal(empty.results.length,0);assert.match(empty.summary,/不会自动放宽/)});
test('cross-noon lessons, excluded topics, costs and conflicts remove courses',async()=>{const across={...first,id:2,sessions:[{start_at:'2026-10-10T03:00:00Z',end_at:'2026-10-10T05:00:00Z'}]};const paid={...first,id:3,fee:20};const music={...first,id:4,title:'古琴入门',tags:'古琴,音乐'};const d=await recommendCourses([first,across,paid,music],ruleIntent('免费上午课，不想学音乐'),c=>c.id===1);assert.equal(d.results.length,0);assert.ok(d.excluded.find(c=>c.id===1).reasons.includes('与个人课表冲突'));assert.ok(d.excluded.find(c=>c.id===4).reasons.includes('属于不想学的内容'))});
test('actual model path and malformed-model fallback report different modes',async()=>{let calls=0;const valid=ruleIntent('免费初级书法课');const env={AI:{async run(){calls++;return {response:JSON.stringify(valid)}}}};const real=await resolveIntent('帮我找不用花钱的写字课',env);assert.equal(real.mode,'AI+规则');assert.equal(calls,1);const bad=await resolveIntent('书法',{AI:{async run(){return {response:'{"courseId":999}'}}}});assert.equal(bad.mode,'规则模式');assert.throws(()=>validateIntent({...valid,interests:['模型编造的课程']}))});
test('model rewrites never override fixed course facts and factual field text is rejected',async()=>{const clean=await plainCourse(first,{AI:{async run(){return {response:'{"intro":"先学握笔，再练习简单的笔画。"}'}}}});assert.equal(clean.mode,'AI+规则');const bad=await plainCourse(first,{AI:{async run(){return {response:'{"intro":"王老师每天9点开课，免费。"}'}}}});assert.equal(bad.mode,'规则模式');assert.equal(bad.intro,first.description);assert.equal(first.fee,0)});
