const $=s=>document.querySelector(s);
const userId=1;
let large=false,detailId=null,detailReturnFocus=null;
const esc=value=>String(value==null?'':value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// XHR also works in older mobile WebViews and on LAN HTTP, with a bounded timeout.
function api(path,options={}){return new Promise((resolve,reject)=>{const r=new XMLHttpRequest();r.open(options.method||'GET',path,true);r.timeout=18000;for(const [k,v]of Object.entries(options.headers||{}))r.setRequestHeader(k,v);r.onload=()=>{try{const data=JSON.parse(r.responseText);if(r.status<200||r.status>=300)reject(Error(data.error||'请求失败'));else resolve(data)}catch(e){reject(Error('服务返回格式不正确，请刷新后重试'))}};r.onerror=()=>reject(Error('连接失败，请检查网络。局域网版需要手机与电脑连接同一Wi-Fi。'));r.ontimeout=()=>reject(Error('请求超时，请重试；仍可直接浏览已加载的课程。'));r.send(options.body||null)})}
const post=(path,data)=>api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
function fmt(value){const d=new Date(new Date(value).getTime()+8*3600000);if(Number.isNaN(d.getTime()))return '时间待确认';return `${d.getUTCMonth()+1}月${d.getUTCDate()}日 周${'日一二三四五六'[d.getUTCDay()]} ${String(d.getUTCHours()).padStart(2,'0')}:${String(d.getUTCMinutes()).padStart(2,'0')}`}
function card(c){const tags=String(c.tags||'').split(',').filter(Boolean).map(x=>`<span class="tag">${esc(x)}</span>`).join('');const first=(c.sessions||[])[0];return `<article class="card"><h3>${esc(c.title)}</h3><div>${tags}</div><p class="meta">${first?fmt(first.start_at):'时间待确认'}<br>${esc(c.location)}</p><p class="description">${esc(c.description)}</p><p class="meta">${esc(c.teacher)} · ${esc(c.level)}<br>剩余 ${c.remaining} 个名额 · ${Number(c.fee)>0?esc(c.fee)+'元':'免费公益课程'}</p><div class="actions"><button class="secondary" onclick="showCourse(${c.id})">详情 / AI说明</button><button ${c.mine?'disabled':''} onclick="enroll(${c.id})">${c.mine?'已报名':c.remaining<=0?'加入候补':'预约课程'}</button></div></article>`}
async function load(){try{const d=await api('/api/courses?userId='+userId+($('#category').value?'&category='+encodeURIComponent($('#category').value):''));$('#courses').innerHTML=d.courses.map(card).join('')||'<p>暂时没有符合条件的课程。</p>';$('#loadStatus').textContent='已加载 '+d.courses.length+' 门演示课程';$('#loadStatus').className='muted'}catch(e){$('#loadStatus').className='notice';$('#loadStatus').innerHTML=esc(e.message)+' <button class="secondary" onclick="load()">重新加载</button>'}await loadSchedule()}
async function loadSchedule(){try{const d=await api('/api/me/schedule?userId='+userId);$('#schedule').innerHTML=d.courses.length?d.courses.map(c=>`<div class="schedule-item"><div><strong>${esc(c.title)}</strong><div class="meta">${esc(c.location)} · ${esc(c.teacher)}</div><div>${String(c.schedule||'').split(',').map(x=>fmt(x.split('|')[0])).join('、')}</div></div><div><span class="status">已报名</span><br><button class="secondary" onclick="cancel(${c.enrollment_id})">取消报名</button></div></div>`).join(''):'<p class="muted">还没有报名课程。找到喜欢的课后，点击“预约课程”。</p>'}catch(e){$('#schedule').innerHTML='<p class="notice">课表暂未加载：'+esc(e.message)+'</p>'}}
async function enroll(id){if(!confirm('确定预约这门演示课程吗？满额时将加入候补。'))return;try{alert((await post('/api/enrollments',{userId,courseId:id})).message);await load();if(detailId===id)await showCourse(id)}catch(e){alert(e.message)}}
async function cancel(id){if(!confirm('确定取消这门课程吗？'))return;try{alert((await api('/api/enrollments/'+id+'?userId='+userId,{method:'DELETE'})).message);await load()}catch(e){alert(e.message)}}
function setPrompt(text){$('#query').value=text;$('#query').focus()}
function refine(text){const old=$('#query').value.trim();$('#query').value=(old?old+'；':'')+text;search()}
async function search(){const text=$('#query').value.trim();if(!text){$('#modeText').textContent='先说说你想学什么，或点击一个示例。';$('#query').focus();return}const button=$('#searchBtn');button.disabled=true;button.textContent='正在理解需求…';$('#modeText').textContent='正在检查条件、课程时间和个人课表…';try{const d=await post('/api/ai/search',{userId,text});$('#modeText').textContent=d.notice;$('#providerBadge').textContent=d.mode==='AI+规则'?'AI 模型已参与':'规则回退模式';const labels=(d.labels||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('');const rows=(d.results||[]).map(c=>`<article class="recommend-row"><div class="recommend-head"><h3>${esc(c.title)}</h3><span class="score">规则得分 ${c.score}</span></div><p>${esc(c.reason)}</p><p class="meta">${esc(c.location)} · ${(c.sessions||[]).map(s=>fmt(s.start_at)).join(' / ')}</p><p class="factors">${(c.factors||[]).map(f=>esc(f.label)+' +'+f.points).join(' · ')}</p><div class="actions"><button class="secondary" onclick="showCourse(${c.id})">了解这门课</button><button onclick="enroll(${c.id})">预约课程</button></div></article>`).join('');$('#recommend').classList.remove('hidden');$('#recommend').innerHTML=`<strong>${esc(d.summary||'选课结果')}</strong><div class="intent-tags">${labels||'<span class="muted">还没有明确条件，可以继续补充。</span>'}</div><p class="meta">本次模式：${esc(d.mode)}${d.model?' · '+esc(d.model):''} · 用时 ${((d.elapsedMs||0)/1000).toFixed(1)}秒</p>${rows}${d.accessibilityNote?'<p class="notice">'+esc(d.accessibilityNote)+'</p>':''}${d.question?'<p><b>再问你一句：</b>'+esc(d.question)+'</p><div class="quick-prompts"><button class="chip" onclick="refine(\'想学书法\')">书法</button><button class="chip" onclick="refine(\'想学音乐\')">音乐</button><button class="chip" onclick="refine(\'只能上午去\')">上午方便</button></div>':''}<details><summary>看看助手怎样筛选</summary><ol class="trace">${(d.trace||[]).map(t=>'<li><b>'+esc(t.label)+'</b>：'+esc(t.detail)+'</li>').join('')}</ol><ul class="excluded">${(d.excluded||[]).map(c=>'<li>'+esc(c.title)+'：'+esc(c.reasons.join('；'))+'</li>').join('')}</ul></details>`}catch(e){$('#modeText').textContent=e.message+' 可以直接浏览下方课程。'}finally{button.disabled=false;button.textContent='帮我选课'}}
async function showCourse(id){try{const d=await api('/api/courses/'+id+'?userId='+userId),c=d.course;detailId=id;if($('#detailOverlay').classList.contains('hidden'))detailReturnFocus=document.activeElement;$('#detailTitle').textContent=c.title;const facts=[['教师',c.teacher],['地点',c.location],['适合人群',c.audience],['费用',Number(c.fee)>0?c.fee+'元':'免费公益课程'],['剩余名额',c.remaining+'个'],['上课时间',(c.sessions||[]).map(s=>fmt(s.start_at)+' 至 '+fmt(s.end_at)).join('；')]];$('#detailContent').innerHTML='<dl class="facts">'+facts.map(([k,v])=>'<dt>'+esc(k)+'</dt><dd>'+esc(v)+'</dd>').join('')+'</dl><h3>课程原始说明</h3><p>'+esc(c.description)+'</p><button class="secondary" onclick="explainCourse('+id+')">让 AI 用简单的话讲讲</button><div id="simpleIntro" class="simple-intro hidden" aria-live="polite"></div><div class="actions"><button onclick="enroll('+id+')">'+(c.remaining<=0?'加入候补':'预约课程')+'</button><button class="secondary" onclick="speakCourse('+id+')">朗读说明</button></div>';$('#detailOverlay').classList.remove('hidden');$('#closeDetail').focus()}catch(e){alert(e.message)}}
async function explainCourse(id){const box=$('#simpleIntro');box.classList.remove('hidden');box.textContent='正在整理简明说明…';try{const d=await post('/api/ai/explain',{courseId:id,userId});if(detailId!==id)return;box.innerHTML='<b>'+(d.mode==='AI+规则'?'AI 简明说明':'原始说明（模型暂不可用）')+'</b><p>'+esc(d.intro)+'</p><small>上课时间、地点、费用和报名条件请以上方课程记录为准。</small>'}catch(e){box.textContent=e.message}}
function closeCourse(){detailId=null;$('#detailOverlay').classList.add('hidden');if(detailReturnFocus)detailReturnFocus.focus()}
function speak(text){if('speechSynthesis'in window&&typeof SpeechSynthesisUtterance!=='undefined'){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='zh-CN';speechSynthesis.speak(u)}else alert('此设备暂不支持朗读，请阅读文字说明。')}
async function speakCourse(id){try{const d=await api('/api/courses/'+id);speak(d.course.title+'。'+d.course.description)}catch(e){alert(e.message)}}
async function showAdmin(){try{const d=await api('/api/admin/courses');$('#resident').classList.add('hidden');$('#admin').classList.remove('hidden');$('#adminCourses').innerHTML=d.courses.map(c=>`<div class="admin-row"><span><b>${esc(c.title)}</b><br><small>${esc(c.category)} · ${esc(c.teacher)} · 已报名 ${c.active_count}/${c.capacity}</small></span><span>${c.status==='published'?'已发布':'已下架'} <button class="secondary" onclick="toggleCourse(${c.id},'${c.status==='published'?'published':'closed'}')">${c.status==='published'?'下架':'重新发布'}</button></span></div>`).join('')}catch(e){alert(e.message)}}
async function toggleCourse(id,status){try{await api('/api/admin/courses/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:status==='published'?'closed':'published'})});await showAdmin()}catch(e){alert(e.message)}}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'&&quoted&&next==='"'){cell+='"';i++;continue}if(ch==='"'){quoted=!quoted;continue}if(ch===','&&!quoted){row.push(cell.trim());cell='';continue}if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell.trim());cell='';if(row.some(Boolean))rows.push(row);row=[];continue}cell+=ch}if(cell||row.length){row.push(cell.trim());rows.push(row)}const headers=rows.shift()||[];return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||''])))}
$('#searchBtn').onclick=search;$('#category').onchange=load;$('#fontBtn').onclick=()=>{large=!large;document.body.classList.toggle('large',large);$('#fontBtn').textContent=large?'标准字号':'大字模式';try{localStorage.setItem('wenxiangLarge',large?'1':'0')}catch{}};try{if(localStorage.getItem('wenxiangLarge')==='1')$('#fontBtn').click()}catch{}
document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>setPrompt(b.dataset.prompt));$('#speakBtn').onclick=()=>speak(Array.from(document.querySelectorAll('#courses h3')).map(x=>x.textContent).join('，'));$('#adminBtn').onclick=showAdmin;$('#residentBtn').onclick=()=>{$('#admin').classList.add('hidden');$('#resident').classList.remove('hidden');load()};$('#closeDetail').onclick=closeCourse;$('#detailOverlay').onclick=e=>{if(e.target===$('#detailOverlay'))closeCourse()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeCourse()});
$('#courseForm').onsubmit=async e=>{e.preventDefault();try{const b=Object.fromEntries(new FormData(e.target));for(const k of ['startAt','endAt','openAt','closeAt'])b[k]=new Date(b[k]).toISOString();await post('/api/admin/courses',b);alert('课程已发布');e.target.reset();await showAdmin()}catch(x){alert(x.message)}};
$('#importBtn').onclick=async()=>{const file=$('#csvFile').files[0];if(!file)return alert('请先选择 CSV 文件');try{const d=await post('/api/admin/courses/import',{courses:parseCsv(await file.text())});alert('已导入 '+d.created+' 门课程');await showAdmin()}catch(e){alert(e.message)}};
api('/api/health').then(h=>{$('#providerBadge').textContent=h.mode==='规则模式'?'本地规则模式':'模型已接入';}).catch(()=>{$('#providerBadge').textContent='连接待检查'});load();
