const $=s=>document.querySelector(s);const userId=1;let large=false;
async function api(path,opts){const r=await fetch(path,opts);const d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d}
function fmt(v){return new Date(v).toLocaleString('zh-CN',{month:'numeric',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit'})}
function card(c){const tags=(c.tags||'').split(',').filter(Boolean).map(x=>`<span class="tag">${x}</span>`).join('');const first=c.sessions?.[0];return `<article class="card"><h3>${c.title}</h3><div>${tags}</div><p class="meta">${first?fmt(first.start_at):''}　${c.location}</p><p class="meta">${c.teacher} · ${c.level} · ${c.audience}</p><p>${c.description}</p><p class="meta">剩余 ${c.remaining} 个名额　${c.fee?`费用 ${c.fee} 元`:'公益课程'}</p><div class="actions"><button onclick="enroll(${c.id})">${c.mine?'已报名':'预约课程'}</button><button class="secondary" onclick="speak(${JSON.stringify(c.title+'。'+c.description)})">朗读</button></div></article>`}
async function showCourse(id){try{const d=await api('/api/courses/'+id+'?userId='+userId),c=d.course;const times=(c.sessions||[]).map(x=>fmt(x.start_at)+' 至 '+new Date(x.end_at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})).join('\n');alert(`${c.title}\n\n教师：${c.teacher}\n地点：${c.location}\n适合：${c.audience}\n费用：${c.fee?c.fee+' 元':'公益课程'}\n剩余名额：${c.remaining}\n上课时间：\n${times}\n\n${c.description}`)}catch(e){alert(e.message)}}
async function load(){const d=await api('/api/courses?userId='+userId+($('#category').value?'&category='+encodeURIComponent($('#category').value):''));$('#courses').innerHTML=d.courses.map(card).join('')||'<p>暂时没有符合条件的课程。</p>';loadSchedule()}
async function loadSchedule(){const d=await api('/api/me/schedule?userId='+userId);$('#schedule').innerHTML=d.courses.length?d.courses.map(c=>`<div class="schedule-item"><div><strong>${c.title}</strong><div class="meta">${c.location} · ${c.teacher}</div><div>${(c.schedule||'').split(',').map(x=>fmt(x.split('|')[0])).join('、')}</div></div><div><span class="status">已报名</span><br><button class="secondary" onclick="cancel(${c.enrollment_id})">取消报名</button></div></div>`).join(''):'<p class="muted">还没有报名课程。</p>'}
async function enroll(id){try{const d=await api('/api/enrollments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId,courseId:id})});alert(d.message);load()}catch(e){alert(e.message)}}async function cancel(id){if(!confirm('确定取消这门课程吗？'))return;try{alert((await api('/api/enrollments/'+id+'?userId='+userId,{method:'DELETE'})).message);load()}catch(e){alert(e.message)}}
async function search(){const text=$('#query').value.trim();if(!text){load();return}try{const d=await api('/api/ai/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId,text})});$('#modeText').textContent=d.notice;$('#recommend').classList.remove('hidden');$('#recommend').innerHTML=`<strong>AI 找课结果（${d.mode}）</strong><p>我理解你的需求：${d.intent.interest||'综合文化课程'}，${d.intent.time||'时间不限'}，${d.intent.level||'入门'}。</p>${d.results.length?d.results.map(c=>`<div class="recommend-row"><b>${c.title}</b>　${c.reason} <button onclick="enroll(${c.id})">预约</button></div>`).join(''):'<p>暂时没有合适课程，可以试试放宽条件。</p>'}`}catch(e){alert(e.message)}}
function speak(text){if('speechSynthesis' in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text))}else alert('当前设备不支持浏览器朗读，请直接阅读文字。')}
async function showAdmin(){ $('#resident').classList.add('hidden');$('#admin').classList.remove('hidden');const d=await api('/api/admin/courses');$('#adminCourses').innerHTML=d.courses.map(c=>`<div class="admin-row"><span><b>${c.title}</b><br><small>${c.category} · ${c.teacher} · 已报名 ${c.active_count}/${c.capacity}</small></span><span>${c.status==='published'?'已发布':'已下架'} <button class="secondary" onclick="toggleCourse(${c.id},'${c.status}')">${c.status==='published'?'下架':'重新发布'}</button></span></div>`).join('')}
async function toggleCourse(id,status){try{await api('/api/admin/courses/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:status==='published'?'closed':'published'})});showAdmin()}catch(e){alert(e.message)}}
$('#searchBtn').onclick=search;$('#category').onchange=load;$('#fontBtn').onclick=()=>{large=!large;document.body.classList.toggle('large',large);$('#fontBtn').textContent=large?'标准字号':'大字模式'};$('#speakBtn').onclick=()=>speak([...document.querySelectorAll('#courses h3')].map(x=>x.textContent).join('，'));$('#adminBtn').onclick=showAdmin;$('#residentBtn').onclick=()=>{$('#admin').classList.add('hidden');$('#resident').classList.remove('hidden');load()};$('#courseForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),b=Object.fromEntries(f);for(const k of ['startAt','endAt','openAt','closeAt'])b[k]=new Date(b[k]).toISOString();try{await api('/api/admin/courses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});alert('课程已发布');e.target.reset();showAdmin()}catch(x){alert(x.message)}};load();

function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'&&quoted&&next==='"'){cell+='"';i++;continue}if(ch==='"'){quoted=!quoted;continue}if(ch===','&&!quoted){row.push(cell.trim());cell='';continue}if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell.trim());cell='';if(row.some(Boolean))rows.push(row);row=[];continue}cell+=ch}if(cell||row.length){row.push(cell.trim());rows.push(row)}const headers=rows.shift()||[];return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||''])))}
const importBtn=document.querySelector('#importBtn');if(importBtn)importBtn.onclick=async()=>{const file=document.querySelector('#csvFile').files[0];if(!file)return alert('请先选择 CSV 文件');try{const courses=parseCsv(await file.text());const d=await api('/api/admin/courses/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({courses})});alert(`已导入 ${d.created} 门课程`);showAdmin()}catch(e){alert(e.message)}};
